GET http://localhost:3000/api/categories
###
GET http://localhost:3000/api/search?query=Как собрать камни
###
GET http://localhost:3000/api/search?query=12312313
###
GET http://localhost:3000/api/search?query=
###
GET http://localhost:3000/api/search


###
GET http://localhost:3000/api/offers
###
GET http://localhost:3000/api/offers/3DD_SH
###
GET http://localhost:3000/api/offers/1
###
DELETE http://localhost:3000/api/offers/rFVOIO
###
GET http://localhost:3000/api/offers/rFVOIO
###
POST http://localhost:3000/api/offers
content-type: application/json

{
    "name": "test"
}
###
POST http://localhost:3000/api/offers
content-type: application/json

{
    "picture": "test",
    "title": "Продам гараж",
    "description": "Любые проверки на месте. Пользовались 2-3 раза",
    "category": [
      "Авто"
    ],
    "sum": 1000,
    "type": "OFFER"
}
###
PUT  http://localhost:3000/api/offers/fyBvB4
content-type: application/json

{
    "picture": "test 2",
    "title": "Продам гараж",
    "description": "Пользовались 2-3 раза",
    "category": [
      "Авто"
    ],
    "sum": 1001,
    "type": "OFFER"
}
###
GET http://localhost:3000/api/offers/3DD_SH/comments
###
DELETE http://localhost:3000/api/offers/3DD_SH/comments/k7dHQQ
###
POST http://localhost:3000/api/offers/3DD_SH/comments
content-type: application/json

{
    "text": "test comment 123231"
}

